FROM nginx:1.19-alpine

#config
COPY applications-go/videos-web/nginx.conf /etc/nginx/nginx.conf

#content
COPY applications-go/videos-web/*.html /usr/share/nginx/html/
COPY applications-go/videos-web/*.css /usr/share/nginx/html/
