FROM golang:1.15-alpine as build
RUN apk add --no-cache git

WORKDIR /src 
ENV GOPROXY=https://goproxy.io

COPY applications-go/videos-api/go.sum /src/
COPY applications-go/videos-api/go.mod /src/
RUN go mod download

COPY applications-go/videos-api/app.go /src

RUN go build -o app

FROM alpine:3.12

RUN mkdir -p /app
COPY --from=build /src/app /app/app
CMD ["./app/app"]
