FROM golang:1.15-alpine as build
RUN apk add --no-cache git


ENV GOPROXY=https://goproxy.io

COPY applications-go /src

WORKDIR /src/applications-go/playlists-api/

RUN go mod download
RUN go build -o app

FROM alpine:3.12

RUN mkdir -p /app
COPY --from=build /src/app /app/app
CMD ["./app/app"]
